### PR TITLE
fix: Adds null check to `removeStyleElement`

### LINKED ISSUE #182: CSS modules and composes colliding with style-loader?
**Do you want to request a *feature* or report a *bug*?**
Possible bug.

**What is the current behavior?**
When using CSS Modules with `composes` alongside `style-loader` I get the following error in the browser console:

```
Dynamic page loading failed TypeError: Cannot read property 'removeChild' of null
    at removeStyleElement (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:123:25)
    at remove (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:169:4)
    at Array.updateStyle (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:181:4)
    at addStylesToDom (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:69:22)
    at module.exports (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:37:2)
    at eval (eval at ./app/containers/Packages/styles.css (4.chunk.js:69), <anonymous>:7:77)
    at Object../app/containers/Packages/styles.css (4.chunk.js:69)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
    at Object.eval (eval at ./app/containers/Packages/index.js (4.chunk.js:62), <anonymous>:13:70)
```

If I remove the `composes` from the relevant css files the page loads without errors.

**If the current behavior is a bug, please provide the steps to reproduce.**
I haven’t tried this with a clean repo, but it happens when I use this loader setup:

```
test: /\.css/,
exclude: /node_modules/,
use: [
	'style-loader',
	{
		loader: 'css-loader',
		options: {
			modules: true,
			localIdentName: '[folder]__[local]___[hash:base64:5]',
			importLoaders: 2
		}
	},
	'postcss-loader'
]
```

IWth that, any `composes` property that loads a style from an external file will cause the error. Something like this:

`composes: default from "styles/contentBlocks.css";`

FWIW, If I add this check to `removeStyleElement()` in `addStyles.js` everything works:

```
function removeStyleElement(styleElement) {
	if (styleElement.parentNode === null) return false; // This line
	styleElement.parentNode.removeChild(styleElement);
	var idx = styleElementsInsertedAtTop.indexOf(styleElement);
	if(idx >= 0) {
		styleElementsInsertedAtTop.splice(idx, 1);
	}
}
```

**What is the expected behavior?**
For `composes` to work without causing issues for `style-loader`.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
- MacOS Sierra v10.12.3
- webpack v2.2.1
- style-loader v0.13.2
- css-loader v0.26.2
- postcss-loader v1.3.3
- Node v6.9.4

### PR DESCRIPTION
**Pull request by brandondurham**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
Private function… no tests.

**If relevant, did you update the README?**
Not relevant.

**Summary**
style-loader was choking on the CSS Modules `composes` feature and throwing a fatal error. Adding a check to the `removeStyleElement` function in `lib/addStyles.js` seems to solve the problem.

**Does this PR introduce a breaking change?**
No.

Closes #182

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@brandondurham Please sign the CLA, in case the bot bugs close and reopen the PR to trigger it again

File: lib/addStyles.js [hunk 1]
```diff
@@ -166,11 +166,11 @@ function insertStyleElement (options, style) {
 }
 
 function removeStyleElement (style) {
+	if (style.parentNode === null) return false;
 	style.parentNode.removeChild(style);
 
 	var idx = stylesInsertedAtTop.indexOf(style);
-
-	if(idx >= 0) {
+	if (idx >= 0) {
```
Comment (evilebottnawi) [inline lib/addStyles.js]: Don't change not related line to PR

Comment (brandondurham) [inline lib/addStyles.js]: Sorry about that. Subconscious flick of the wrist. Should be good to go.

**Comment by michael-ciniawsky** [comment]
@brandondurham Thx
