### PR TITLE
fix(addStyles): revert merged loops

### LINKED ISSUE #234: Uncaught TypeError: Cannot read property 'sourceMap' of undefined
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After upgrading to v0.18.0 and trying to run my application with webpack-dev-server it produces the following error and I get a blank page.
```
Uncaught TypeError: Cannot read property 'sourceMap' of undefined
    at addStyle (eval at ./node_modules/style-loader/lib/addStyles.js (main.js:6068), <anonymous>:237:6)
    at addStylesToDom (eval at ./node_modules/style-loader/lib/addStyles.js (main.js:6068), <anonymous>:107:25)
    at module.exports (eval at ./node_modules/style-loader/lib/addStyles.js (main.js:6068), <anonymous>:67:2)
    at eval (eval at ./src/containers/pages/About/About.scss (main.js:6812), <anonymous>:12:81)
    at Object../src/containers/pages/About/About.scss (main.js:6812)
    at __webpack_require__ (manifest.js:692)
    at fn (manifest.js:115)
    at eval (eval at ./src/containers/pages/About/About.js (main.js:6805), <anonymous>:17:14)
    at Object../src/containers/pages/About/About.js (main.js:6805)
    at __webpack_require__ (manifest.js:692)
```

I looked at `addStyles.js`, but could not figure out why `obj` would be undefined.
This is the relevant part of my webpack config (all loaders are at latest version):
```
{
	test: /\.scss$/,
		use: ExtractTextPlugin.extract(
	{
		fallback: 'style-loader',
		use: [
			{
				loader: 'css-loader',
				options: {
					modules: true,
					importLoaders: 3,
					localIdentName: production ? '[hash:6]' : '[local]-[hash:5]',
					sourceMap: true
				}
			},
			{ loader: 'postcss-loader', options: { sourceMap: true } },
			{ loader: 'resolve-url-loader', options: { keepQuery: true } },
			{ loader: 'sass-loader', options: { outputStyle: 'expanded', sourceMap: true } }
		]
	})
}
```

**Other relevant information**
webpack: 2.5.1
node: v7.9.0
MacOS Sierra

### LINKED ISSUE #235: SourceMap problem when hot reloading
**What is the current behavior?**
I just updated to 0.18.0 from 0.17.0 - and now I'm getting crashing errors, like so:

```
TypeError: Cannot read property 'sourceMap' of undefined
    at addStyle (webpack:///./~/style-loader/lib/addStyles.js?:237:6)
    at addStylesToDom (webpack:///./~/style-loader/lib/addStyles.js?:107:25)
    at update (webpack:///./~/style-loader/lib/addStyles.js?:82:4)
    at eval (webpack:///./src/client/styles/entry.scss?:21:4)
    at Object.hotApply [as apply] (http://localhost:8080/dist/bundle-8-movies-breadcrumbs.js:565:16)
    at cb (webpack:///./~/webpack-hot-middleware/process-update.js?:52:36)
    at eval (webpack:///./~/webpack-hot-middleware/process-update.js?:68:13)
    at <anonymous>
From previous event:
    at check (webpack:///./~/webpack-hot-middleware/process-update.js?:67:16)
    at module.exports (webpack:///./~/webpack-hot-middleware/process-update.js?:28:5)
    at processMessage (webpack:///./~/webpack-hot-middleware/client.js?:228:9)
    at Array.handleMessage (webpack:///./~/webpack-hot-middleware/client.js?:111:7)
    at EventSource.handleMessage (webpack:///./~/webpack-hot-middleware/client.js?:74:19)
handleError @ process-update.js:116
applyCallback @ process-update.js:45
tryCatcher @ bluebird.js:5253
Promise._settlePromiseFromHandler @ bluebird.js:3275
Promise._settlePromise @ bluebird.js:3332
Promise._settlePromiseCtx @ bluebird.js:3369
(anonymous) @ bluebird.js:165
Promise resolved (async)
schedule @ bluebird.js:4481
Async.invoke @ bluebird.js:164
Promise._then @ bluebird.js:3024
Promise.then @ bluebird.js:2888
Promise.caught.Promise.catch @ bluebird.js:2869
cb @ process-update.js:59
(anonymous) @ process-update.js:68
tryCatcher @ bluebird.js:5253
Promise._settlePromiseFromHandler @ bluebird.js:3275
Promise._settlePromise @ bluebird.js:3332
Promise._settlePromise0 @ bluebird.js:3377
Promise._settlePromises @ bluebird.js:3456
(anonymous) @ bluebird.js:175
Promise resolved (async)
schedule @ bluebird.js:4481
Async.settlePromises @ bluebird.js:174
Promise._fulfill @ bluebird.js:3403
Promise._resolveCallback @ bluebird.js:3195
(anonymous) @ bluebird.js:3247
hotUpdateDownloaded @ bundle-8-movies-breadcrumbs.js:295
hotAddUpdateChunk @ bundle-8-movies-breadcrumbs.js:263
webpackHotUpdateCallback @ bundle-8-movies-breadcrumbs.js:8
(anonymous) @ :8080/dist/0.f96803f3580a00c4cdb5.hot-update.js:1
bluebird.js:1542 Unhandled rejection TypeError: Cannot read property 'sourceMap' of undefined
    at addStyle (webpack:///./~/style-loader/lib/addStyles.js?:237:6)
    at addStylesToDom (webpack:///./~/style-loader/lib/addStyles.js?:107:25)
    at update (webpack:///./~/style-loader/lib/addStyles.js?:82:4)
    at eval (webpack:///./src/client/styles/entry.scss?:21:4)
    at Object.hotApply [as apply] (http://localhost:8080/dist/bundle-8-movies-breadcrumbs.js:565:16)
    at cb (webpack:///./~/webpack-hot-middleware/process-update.js?:52:36)
    at eval (webpack:///./~/webpack-hot-middleware/process-update.js?:68:13)
    at <anonymous>
From previous event:
    at check (webpack:///./~/webpack-hot-middleware/process-update.js?:67:16)
    at module.exports (webpack:///./~/webpack-hot-middleware/process-update.js?:28:5)
    at processMessage (webpack:///./~/webpack-hot-middleware/client.js?:228:9)
    at Array.handleMessage (webpack:///./~/webpack-hot-middleware/client.js?:111:7)
    at EventSource.handleMessage (webpack:///./~/webpack-hot-middleware/client.js?:74:19)
```

**What is the expected behavior?**
Styles should reload without crashing the hot reloading

I tried updating the `css-loader` to the latest version (that was just released for seemingly the same problem) but it still crashes.

I have now reverted back to 0.17.0 and there are no problems.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

`"webpack": "^2.5.1",`
NodeJS v7.7.3

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
Fixes #234, #235

### CODE REVIEW

File: lib/addStyles.js [hunk 1]
```diff
@@ -102,14 +102,13 @@ function addStylesToDom (styles, options) {
 		if(domStyle) {
 			domStyle.refs++;
 
-			for(var j = 0; j < domStyle.parts.length && item.parts.length; j++) {
```
Comment (evilebottnawi) [inline lib/addStyles.js]: Why we do this? :smile:

Comment (michael-ciniawsky) [inline lib/addStyles.js]: Because I followed your guidance https://github.com/webpack-contrib/style-loader/pull/224#discussion_r114125336 😛 🚀

Comment (evilebottnawi) [inline lib/addStyles.js]: @michael-ciniawsky I'm ashamed, a lot of issues :disappointed: Btw, we need add tests for this, someone in the future may want to do the same and repeat our mistake

Comment (michael-ciniawsky) [inline lib/addStyles.js]: totally wayne 😛 , I'm still wondering while this actually makes a difference ¯\_(ツ)_/¯ test passed on both ways, but seem to **not** cover this :D

Comment (evilebottnawi) [inline lib/addStyles.js]: @michael-ciniawsky have we minimal test repo? maybe we can determine when this happens and add a tests

Comment (michael-ciniawsky) [inline lib/addStyles.js]: Nope I haven't, only used it locally for a few days and it seemed to work fine + `style-loader` tests. But I'm not using `webpack-hot-middleware` or the like

Comment (evilebottnawi) [inline lib/addStyles.js]: @michael-ciniawsky let's wait when we have test repo, then add tests and merge and publish. We have big problems with the tests (in many `webpack-contrib` repos), if we continue to ignore this, it will be very bad
